### ISSUE TITLE
options.workstation is read-only

### ISSUE THREAD

**Issue by kylegoetz** [SamDecrock/node-http-ntlm#34]
/node_modules/httpntlm/httpntlm.js:10
	if(!options.workstation) options.workstation = '';
	                                             ^
TypeError: Cannot assign to read only property 'workstation' of http://localhost:81/UserProfile.aspx
    at Object.exports.method (/node_modules/httpntlm/httpntlm.js:10:47)
    at Object.handler (/server.js:8:12)
    at final_dispatch (/node_modules/node-simple-router/lib/router.js:275:26)
    at Server.dispatch (/node_modules/node-simple-router/lib/router.js:326:14)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)

**Comment by kylegoetz** [comment]
Nevermind.
