### ISSUE TITLE
Unsure how to save data

### ISSUE THREAD

**Issue by chevalierc** [SamDecrock/node-http-ntlm#35]
Sam, 
How would I save the data coming back.
it looks like such:
` y�����\3�k�H�R��)M>���R6�E��/H`
and is an .xlsx excel file. 
Here is my code at the moment. I'm trying to use the FS library to save to disk. Is that wrong?
```
httpntlm.get({
        url: url,
        username: 'chevac03',
        password: 'pw'
    }, function (err, response){
        fs.writeFile(filename, response.body, 'utf8', function (err) {
            if(err)console.log("error writing file");
            callback();
        });
    });
```

**Comment by SamDecrock** [comment]
Try this:

```javascript
httpntlm.get({
    url: url,
    username: 'chevac03',
    password: 'pw',
    binary: true
}, function (err, response){
    fs.writeFile(filename, response.body, function (err) {
        if(err)console.log("error writing file");
    });
});
```

**Comment by chevalierc** [comment]
Sam, Thanks for the reply.
My body is now in hex?
`<Buffer 50 4b 03 04 0a 00 08 08 08 00 9c 31 81 48 00 00 00 00 00 00 00 00 00 00 00 00 18 00 00 00 78 6c 2f 77 6f 72 6b
73 68 65 65 74 73 2f 73 68 65 65 74 31 ... >
`
And produce the error:

```
Unhandled rejection Error: invalid signature: 0x808000a
    at C:\working\ireg\node_modules\exceljs\node_modules\unzip\lib\parse.js:59:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Unhandled rejection Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: �
    at error (C:\working\ireg\node_modules\exceljs\node_modules\sax\lib\sax.js:642:8)
    at strictFail (C:\working\ireg\node_modules\exceljs\node_modules\sax\lib\sax.js:662:22)
    at Object.write (C:\working\ireg\node_modules\exceljs\node_modules\sax\lib\sax.js:935:11)
    at SAXStream.write (C:\working\ireg\node_modules\exceljs\node_modules\sax\lib\sax.js:227:16)
    at write (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_stream_readable
.js:623:24)
    at flow (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_stream_readable.
js:632:7)
    at Entry.pipeOnReadable (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_
stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at emitReadable_ (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_stream_
readable.js:448:10)
    at emitReadable (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_stream_r
eadable.js:444:5)
    at readableAddChunk (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_stre
am_readable.js:187:9)
    at Entry.Readable.push (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_s
tream_readable.js:149:10)
    at Entry.Transform.push (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_
stream_transform.js:145:32)
    at afterTransform (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-stream\lib\_stream
_transform.js:101:12)
    at TransformState.afterTransform (C:\working\ireg\node_modules\exceljs\node_modules\unzip\node_modules\readable-str
eam\lib\_stream_transform.js:79:12)
```

Using the code. If I try to write in an binary encoding I still get the error above.

**Comment by chevalierc** [comment]
Also using the code:
```
httpntlm.get({
            username: config.ntCredentials.username,
            password: config.ntCredentials.password,
            url: config.dsrtFile
        }, function (err, response){
            fs.writeFile(filename, response.body, function (err) {
                if(err)console.log("error writing file");
                callback();
            });
        });
```
I get the error:
````
Unhandled rejection Error: invalid stored block lengths
    at Zlib._handle.onerror (zlib.js:363:17)
```

**Comment by SamDecrock** [comment]
Your body is now binary! If you `console.log()` it, the bytes are represented as Hex characters. This is normal for Node.js  ;-)

Your Excel-file is downloaded properly. Have you tried opening it with Excel? 

The module `exceljs` you are using cannot parse old fashioned xls-files. Only xlsX-files, which are XML files.Maybe you should try this: https://www.npmjs.com/package/excel-parser which supports xls too.

**Comment by chevalierc** [comment]
Wow awesome. May I suggest adding the binary option that to the readme.md? I see it internally but not there.

Again thanks for the help! The module really saved me from a sticky situation..

**Comment by chevalierc** [comment]
Also for future the binary stream it returns plays really well with [https://www.npmjs.com/package/xlsx](XLSX) It can take the binary input as is. No need to save to disk.

**Comment by SamDecrock** [comment]
No problem, I added the binary example as you suggested.

Happy coding!
