### ISSUE TITLE
Unable to use when certificate is invalid

### ISSUE THREAD

**Issue by tikiwade** [SamDecrock/node-http-ntlm#45]
I am getting this error:

{ Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_VERIFY
_LEAF_SIGNATURE' }

I am pretty sure it is because the SSL certificate is not valid. Is there a workaround to allow me to get past this?

**Comment by SamDecrock** [comment]
This can be solved by adding`rejectUnauthorized : false` to the options. They get passed along to [httpreq](https://github.com/SamDecrock/node-httpreq), which passes them along to [node https](https://nodejs.org/api/https.html#https_https_request_options_callback).

**Comment by cwohlman** [comment]
It would be nice if this was documented, I ran into the same issue.
