### ISSUE TITLE
Offset out of bounds on mac

### ISSUE THREAD

**Issue by ErlendEllingsen** [SamDecrock/node-http-ntlm#57]
Simply using the httpntlm-module on a mac fails, whilst on debian it works correctly. I thought it might was a corrupt installation, but after removing and installing again, the same happens.

This is the output

```
buffer.js:764
        return this.asciiWrite(string, offset, length);
                    ^

RangeError: Offset is out of bounds
    at RangeError (native)
    at Buffer.write (buffer.js:764:21)
    at Object.createType1Message (PATH_TO_PROJECT/node_modules/httpntlm/ntlm.js:106:6)
    at sendType1Message (PATH_TO_PROJECT/node_modules/httpntlm/httpntlm.js:42:23)
    at Object.exports.method (PATH_TO_PROJECT/node_modules/httpntlm/httpntlm.js:98:2)
    at Object.<anonymous> (PATH_TO_PROJECTindex.js:4:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
ErlendMBPrivate:project erlendellingsen$ 
```

**Comment by SamDecrock** [comment]
Hmm, are you using some kind of special characters in your domain or workstation? (like é, è, û, ...)

I initially developed it on macOS, so it should work.

**Comment by SamDecrock** [comment]
I fixed some thing, let me know if it works!
