### ISSUE TITLE
Can't exec example client

### ISSUE THREAD

**Issue by dmvstar** [SamDecrock/node-http-ntlm#84]
After execute code from example like 

var httpntlm = require('httpntlm');
httpntlm.get({
    url: "https://someurl.com",
    username: 'm$',
    password: 'stinks',
    workstation: 'choose.something',
    domain: 'domain'
}, function (err, res){
    console.log(err);
    if(err) return err;
    console.log(res.headers);
    console.log(res.body);
});

I have a error and
I don't know how to fix it.

Error: www-authenticate not found on response of second request
    at sendType3Message (C:\home\programs\node\node_modules\httpntlm\httpntlm.js:70:20)
    at Immediate._onImmediate (C:\home\programs\node\node_modules\httpntlm\httpntlm.js:101:4)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by dmvstar** [comment]
Resolved
The problem was the incorrect behavior of the IIS server

**Comment by dmvstar** [comment]
Resolved
The problem was the incorrect behavior of the IIS server
